const express= require('express')
const router=express.Router()
const {createStudent,getStudent,getstudentbyId,updateStudentbyId,deleteStudentbyId,createcourse,getcourse,createEnrollment,getstudentbyidcourse}=require('../controller/studentcontroller')
const { get } = require('node:http')
router.post('/',createStudent)
router.get('/',getStudent)
router.get('/:id',getstudentbyId)
router.put('/:id',updateStudentbyId)
router.delete('/:id',deleteStudentbyId)
router.post('/course',createcourse)
router.get('/course',getcourse)
router.post('/enrollment',createEnrollment)
router.get('/enrollment/:id/course',getstudentbyidcourse)
module.exports=router;
